version: '3'
services:
  app:
    build:
      context: .
      args:
        JAR_FILE: /demo-0.0.1-SNAPSHOT.jar
    restart: on-failure
    ports:
      - 8080:8080
  cassandra:
    image: "cassandra"